[package]
name = "ateam-controls"
version = "0.1.0"
edition = "2024"

[features]
default = []
std = []
serde = ["dep:serde", "nalgebra/serde-serialize"]
defmt = ["dep:defmt"]

[dependencies]
libm = "0.2"
nalgebra = { version = "0.34.0", default-features = false, features = ["libm", "macros"] }
serde = { version = "1", default-features = false, features = ["derive"], optional = true }
defmt = { version = "0.3", optional = true }