"""Python ctypes bindings for the ateam_controls C library.

This package mirrors the ateam-controls-c public API.
"""

from ._bindings import (
    # Error handling
    ControlsError,
    ATEAM_CONTROLS_OK,
    ATEAM_CONTROLS_INVALID_INPUT,
    ATEAM_CONTROLS_SINGULAR,
    ATEAM_CONTROLS_NO_SOLUTION,
    ATEAM_CONTROLS_INVALID_TIME,
    ATEAM_CONTROLS_EXCEEDS_LIMIT,
    # Types
    Vector2C,
    Vector3C,
    Vector4C,
    Vector6C,
    Vector8C,
    Matrix3C,
    Matrix3x4C,
    Matrix4x3C,
    KalmanFilterParams,
    RobotPhysicalParams,
    TrajectoryParams,
    BangBangTraj1D,
    BangBangTraj3D,
    PivotParams,
    PivotTrajectory,
    PIVOT_DIRECTION_FORWARD,
    PIVOT_DIRECTION_BACKWARD,
    LinearParams,
    LinearTrajectory,
    LINEAR_HEADING_MODE_FIXED,
    LINEAR_HEADING_MODE_FACE_POINT,
    # Default parameter constructors
    default_kf_params,
    default_phys_params,
    default_traj_params,
    default_pivot_params,
    default_linear_params,
    # RobotModel functions
    robot_model_new,
    robot_model_free,
    robot_model_update_kf_params,
    robot_model_update_physical_params,
    robot_model_kf_predict,
    robot_model_kf_update,
    robot_model_get_state,
    robot_model_set_state,
    robot_model_transform_wheel2twist,
    robot_model_transform_twist2wheel,
    robot_model_transform_wheel2accel,
    robot_model_transform_accel2wheel,
    robot_model_torques_to_currents,
    # BangBang trajectory functions
    traj_from_target_pose,
    traj_from_target_twist,
    traj_1d_time_shift,
    traj_3d_time_shift,
    traj_end_time,
    traj_state_at,
    traj_accel_at,
    traj_tick,
    traj_sample,
    # Pivot trajectory functions
    pivot_traj_from_target_heading,
    pivot_traj_from_target_point,
    pivot_traj_time_shift,
    pivot_traj_end_time,
    pivot_traj_state_at,
    pivot_traj_accel_at,
    pivot_traj_tick,
    pivot_traj_sample,
    # Linear trajectory functions
    linear_traj_from_line,
    linear_traj_from_point,
    linear_traj_time_shift,
    linear_traj_end_time,
    linear_traj_state_at,
    linear_traj_accel_at,
    linear_traj_tick,
    linear_traj_sample,
)
