// Kalman filter params
pub const PROCESS_NOISE_STDDEV_POS_LINEAR: f32 = 0.001;  // m
pub const PROCESS_NOISE_STDDEV_POS_ANGULAR: f32 = 0.0005;  // rad
pub const PROCESS_NOISE_STDDEV_VEL_LINEAR: f32 = 0.001;  // m/s
pub const PROCESS_NOISE_STDDEV_VEL_ANGULAR: f32 = 0.0005;  // rad/s
pub const MEASUREMENT_NOISE_STDDEV_VISION_POS_LINEAR: f32 = 0.3;  // m  (HIGH LAG)
pub const MEASUREMENT_NOISE_STDDEV_VISION_POS_ANGULAR: f32 = 0.1;  // rad  (HIGH LAG)
pub const MEASUREMENT_NOISE_STDDEV_ENCODER_VEL_ANGULAR: f32 = 1.0;  // rad/s
pub const MEASUREMENT_NOISE_STDDEV_GYRO_VEL_ANGULAR: f32 = 0.015;  // rad/s
